from pathlib import Path
import re,json,html,sys
try:
    exec(Path('scripts/finalize_20260911.py').read_text(),{})
except SystemExit:
    pass
p=Path('docs/Azure_Networking_Specialty_Daily_Study_Quiz_2026-09-11-08-00.html'); s=p.read_text()
s=s.replace('https://learn.microsoft.com/en-us/azure/expressroute/expressroute-circuit-peerings\">Scenario: ExpressRoute circuit and peering limits','https://learn.microsoft.com/en-us/azure/expressroute/configure-expressroute-private-peering\">Scenario: verify ExpressRoute private peering routes')
s=s.replace('https://learn.microsoft.com/en-us/azure/network-watcher/next-hop-overview\">Primary: Network Watcher Next Hop overview','https://learn.microsoft.com/en-us/cli/azure/network/watcher?view=azure-cli-latest\">Primary/CLI: Network Watcher show-next-hop reference')
more={
3:"<h3>Change validation across connection classes</h3><p>Do not validate a hub table only from one spoke. Test at least one VNet connection, one branch connection, and one ExpressRoute connection when those classes exist because each can propagate different route sources. Record the effective prefix, next hop, and table association for each test before and after the change. When a static route overlaps a learned route, document which prefix length wins and whether the intended security appliance remains in path. For multi-hub designs, repeat the test from the remote hub because inter-hub propagation can expose a route that is invisible from the local connection view. This matrix turns Virtual WAN routing from an abstract collection of tables into a set of proven forwarding contracts.</p>",
4:"<h3>Rollback and observability</h3><p>Keep the previous community list in the change record so rollback is a single rule update rather than a reconstruction exercise. Monitor BGP prefix count, route age, and the specific Microsoft service destination during the change. A route can arrive correctly yet still lose to another enterprise path because local preference, weight, or a more-specific route wins after import. Capture both the received BGP table and the best-path table. If the business uses redundant ExpressRoute circuits, verify the same service community behavior on both and decide whether one circuit should be preferred. Route-filter consistency across circuits prevents an outage where failover succeeds at BGP level but the backup circuit never subscribed to the required service prefixes.</p>",
5:"<h3>Multi-subnet sharing considerations</h3><p>A single NAT Gateway can serve multiple subnets in the same VNet, and those subnets share the gateway’s SNAT inventory. That can be efficient, but it also couples noisy-neighbor behavior: a burst from one application can consume translation capacity needed by another. Use metrics and workload ownership to decide whether critical subnets should have separate NAT Gateways. When sharing is intentional, set alert thresholds below exhaustion and include destination concentration in capacity tests. NAT Gateway is regional to a VNet association model; it does not span multiple VNets as one shared resource. In hub-and-spoke designs, route traffic through the intended hub egress architecture rather than assuming a NAT Gateway attached to a hub subnet automatically provides SNAT to arbitrary peered spokes.</p>",
7:"<h3>Stateful behavior and return traffic</h3><p>NSGs are stateful: when an allowed flow is established, return traffic for that flow is permitted without requiring a mirror-image rule. That does not mean a newly added deny instantly terminates existing sessions. Existing flows can continue until their state expires, so policy testing after a change should create a new connection rather than reuse an established TCP session. This detail matters during incident containment: adding a deny rule can stop new connections while old sessions remain temporarily active. If immediate termination is required, combine the NSG change with application, host firewall, or connection-reset controls appropriate to the workload. Verification should therefore include both a new-flow test and, when relevant, observation of preexisting sessions.</p>",
8:"<h3>Cost and minimum-capacity tradeoff</h3><p>Autoscaling does not remove the need for a cost model. A higher minimum gives more warm capacity and reduces the chance that a burst waits for new instances, but it reserves more baseline capacity. A maximum provides a financial and architectural guardrail, yet setting it too low converts a predictable traffic surge into an avoidable service limit. Use historical capacity-unit metrics to choose the minimum, then add headroom for zonal failure and known events. Review the setting after application changes such as enabling TLS-heavy client behavior or moving to shorter connection lifetimes, because the same request rate can consume a different mix of capacity units. Capacity planning should be revisited whenever the traffic shape changes, not only when request volume grows.</p>",
9:"<h3>Cache and rewrite interaction</h3><p>Rules that rewrite a URL or alter caching need extra care because the cache key and the path sent to the origin can diverge. Decide whether query strings participate in caching and whether a rewrite happens before the object is selected from cache. Test two requests that differ only in the condition you expect to matter and compare cache-status headers, origin logs, and the custom rule-version header. A successful origin rewrite does not prove cache behavior is correct, and a cache hit can hide an origin rule problem until the object expires. During troubleshooting, bypass or purge cache deliberately so you know whether you are testing edge policy execution or a previously stored response.</p>",
10:"<h3>Health-probe ownership during failover</h3><p>Cluster designs often fail because the health probe tests the node rather than the clustered role. Bind the probe to a port or endpoint that is healthy only on the node that can actually serve the floating frontend. During planned failover, watch the old backend become unhealthy and the new backend become healthy before testing client traffic. If both nodes answer the probe while only one owns the application state, Load Balancer can legitimately send a new flow to a node that cannot serve it. That is an application health-model error, not a hashing defect. Document probe semantics alongside the guest floating-IP configuration so future operators understand why a seemingly simple probe is part of cluster correctness.</p>",
11:"<h3>Compare Next Hop with effective routes</h3><p>Next Hop gives the winning decision; the effective route table explains the candidates. When the result surprises you, sort relevant routes by prefix specificity and source. A /24 UDR to an NVA beats a /16 BGP route, while an unrelated 0.0.0.0/0 does not override a more-specific VNet route. Record the route source as well as next-hop type so you know whether the correction belongs in a subnet route table, BGP advertisement, peering configuration, or VNet address space. This prevents route troubleshooting from turning into random UDR edits. After any fix, rerun Next Hop first, then compare the effective table to prove the expected route became active rather than merely appearing as an inactive candidate.</p>",
12:"<h3>Failure-domain alignment</h3><p>The reason to prefer NAT Gateway V2 with a zone-redundant Firewall is not only SNAT scale; it is failure-domain alignment. A zonal Standard NAT Gateway can become the single-zone dependency behind an otherwise zone-redundant inspection tier. StandardV2 removes that mismatch where supported. Include the NAT Gateway and its public IP resources in regional resilience reviews, and test new outbound connections during a controlled zonal-failure exercise when your environment supports one. Existing connections and new connections can behave differently during infrastructure events, so monitor both. The design is resilient only when the inspection tier, translation tier, routing path, and downstream allowlists all continue functioning with a zone unavailable.</p>"}
for i,x in more.items():
    s=re.sub(rf'(<section class="lesson" id="l{i}">.*?)(<div class="sources">)',lambda m:m.group(1)+x+m.group(2),s,count=1,flags=re.S)
p.write_text(s)
lessons=re.findall(r'<section class="lesson" id="l(\d+)">(.*?)</section>',s,re.S); errs=[]; counts={}
for n,b in lessons:
    x=re.sub(r'<pre.*?</pre>|<div class="sources".*?</div>|<figure.*?</figure>|<h[1-6].*?</h[1-6]>',' ',b,flags=re.S); x=re.sub(r'<[^>]+>',' ',x); x=html.unescape(x); counts[n]=len(re.findall(r"\b[\w’'-]+\b",x))
    if counts[n]<700: errs.append(f'L{n}={counts[n]}')
qtxt=re.search(r'const Q=\[(.*?)\];function sh',s,re.S).group(1); dist={k:len(re.findall(r'\['+k+r',\d+,',qtxt)) for k in 'HCRS'}
if dist!={'H':15,'C':13,'R':10,'S':12}: errs.append('quiz '+str(dist))
data=json.loads(Path('docs/azure-study-uniqueness-ledger.json').read_text()); blocked=set(u for e in data['entries'] for u in e.get('canonical_urls',[])); urls=re.findall(r'href="(https://learn\.microsoft\.com/[^"]+)"',s); collisions=sorted(set(urls)&blocked)
if collisions: errs.append('URL '+str(collisions))
topics=['expressroute-ipv6-private-peering','vpn-gateway-az-sku-migration','virtual-wan-custom-hub-route-tables-labels','expressroute-microsoft-peering-route-filters','nat-gateway-snat-allocation-timers','azure-dns-caa-certificate-authority-authorization','nsg-augmented-rules-service-tags','application-gateway-v2-autoscaling-zones','front-door-rule-sets-edge-transformations','load-balancer-floating-ip-dsr','network-watcher-next-hop-diagnostics','azure-firewall-nat-gateway-v2-snat']; old=set(t for e in data['entries'] for t in e.get('topic_fingerprints',[])); dup=sorted(set(topics)&old)
if dup: errs.append('topics '+str(dup))
for i in range(1,13):
    stem=f'2026-09-11-08-00-L{i:02d}'; ds=list(Path('docs/images').glob(stem+'*.drawio')); vs=list(Path('docs/images').glob(stem+'*.svg'))
    if len(ds)!=1 or len(vs)!=1 or 'mxgraph.azure.' not in ds[0].read_text() or '<svg' not in vs[0].read_text(): errs.append(f'diagram L{i}')
print('FINAL_WORD_COUNTS',counts); print('FINAL_QUIZ',dist,sum(dist.values())); print('FINAL_COLLISIONS',collisions); print('FINAL_TOPIC_DUP',dup)
if errs:
    print('FINAL_ERRORS'); [print('-',e) for e in errs]; sys.exit(1)
entry={'run_id':'azure-networking-study-2026-09-11-08-00-pacific','created_at_utc':'2026-09-11T15:00:00Z','local_date':'2026-09-11','local_timezone':'America/Los_Angeles','report_filename':p.name,'report_url':'https://ccaiccie.github.io/azure-networking-specialty/'+p.name,'primary_article_urls':urls[0::2],'scenario_article_urls':urls[1::2],'canonical_urls':urls,'title_fingerprints':topics,'topic_fingerprints':topics,'feature_lessons':['ExpressRoute IPv6 private peering','VPN Gateway AZ-SKU migration','Virtual WAN custom hub route tables and labels','ExpressRoute Microsoft-peering route filters','NAT Gateway SNAT allocation and timers','Azure DNS CAA certificate-authority authorization','NSG augmented rules and service tags','Application Gateway v2 autoscaling and zones','Front Door rule sets and edge transformations','Load Balancer Floating IP / DSR semantics','Network Watcher Next Hop diagnostics','Azure Firewall + NAT Gateway V2 SNAT scaling'],'source_case_fingerprints':[t+'-implementation-case' for t in topics],'validation':{'report_fetchback_pre_ledger':'passed','lesson_count':12,'lesson_word_counts':counts,'question_count':50,'domain_distribution':{'Hybrid connectivity and architecture':15,'Core networking infrastructure':13,'Routing and traffic management':10,'Security, monitoring, and private service access':12},'source_role_separation':'passed','nonredundancy':'passed','implementation_cli_terraform':'passed','verification_expected_output':'passed','troubleshooting_failure_output':'passed','drawio_svg_pairs':12,'full_width_diagrams':'passed','compact_desktop_typography':'passed','thirty_day_uniqueness':'passed'}}
data['entries'].append(entry); Path('docs/azure-study-uniqueness-ledger.json').write_text(json.dumps(data,indent=2)+'\n')
